### ISSUE TITLE
Help sshmuxd not working for me

### ISSUE THREAD

**Issue by sandeep048** [joushou/sshmuxd#10]
I have two ssh servers running on my server. Local and a remote forwarded one. Can you kindly let me know what I am doing wrong here.

```
[Wed Apr 13 6:29:30] sandeep@streamfra.me:~$ sshmuxd example_conf.json
panic: open hostkey: no such file or directory

goroutine 1 [running]:
main.main()
        /home/sandeep/.go/src/github.com/joushou/sshmuxd/main.go:99 +0x160

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
[Wed Apr 13 6:29:36] sandeep@streamfra.me:~$
[Wed Apr 13 6:29:36] sandeep@streamfra.me:~$ cat example_conf.json
{
   "address": ":22222",
   "hostkey": "hostkey",
   "authkeys": "authkeys",
   "hosts": [
      {
         "address": "localhost:2222",
         "users": [ "osmc" ]
      },
      {
         "address": "localhost:22",
         "users": [ "sandeep" ]
      }
   ]
}
```

**Comment by kennylevinsen** [comment]
You need to generate a private key for the server. The OpenSSH server does this for you, but sshmuxd is not that fancy. You can just ssh-keygen to make a private key for the server (this should not be your own private key! It should be unique - the example configuration expects the result to be called "hostkey"). 

Likewise, you need an authorized_keys file for it (the example configuration expects this to be called "authkeys"). This is just a file listing all the public keys that can connect - note that the comment (the thing at the end of the public key) is what you need to use in the "users" section to tell if a user is allowed access to a server or not. You change it in the authkeys file if you want, it's just a comment and not part of the key itself.
